import {
  Calendar,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  Github,
  LayoutDashboard,
  ListTodo,
  LogOut,
  MessageCircle,
  Moon,
  Plus,
  Settings,
  Signal,
  Sun,
  Trash2,
  User,
  Users,
  X,
} from "lucide-react";

export const Icons = {
  sun: Sun,
  moon: Moon,
  github: Github,
  tasks: CheckSquare,
  myTasks: ListTodo,
  settings: Settings,
  x: X,
  dashboard: LayoutDashboard,
  kanban: LayoutDashboard,
  plus: Plus,
  calendar: Calendar,
  user: User,
  users: Users,
  signal: Signal,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  messageCircle: MessageCircle,
  logOut: LogOut,
  trash: Trash2,
};
